# Generated by Django 5.0.8 on 2024-08-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_remove_damagedparcelrecord_package_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DamagedParcelRecord',
            new_name='DamagedParcel',
        ),
    ]
