# Generated by Django 5.0.8 on 2024-08-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="max_bonus_value",
        ),
    ]
