# Generated by Django 5.0.7 on 2024-07-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Parcel",
            new_name="Hub",
        ),
    ]
